import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('punkt')
nltk.download('stopwords')

data = [
    "La Revolución Industrial fue un periodo histórico",
    "La Revolución Francesa marcó un cambio político importante",
    "La Segunda Guerra Mundial tuvo un gran impacto en el mundo",
    "El descubrimiento de América cambió la historia para siempre",
    "La Revolución Rusa de 1917 transformó el sistema político en Rusia",
    "El Renacimiento fue un período de gran florecimiento cultural en Europa",
    "La Guerra Fría fue un conflicto geopolítico entre Estados Unidos y la Unión Soviética",
    "La caída del Muro de Berlín en 1989 marcó el fin de la Guerra Fría",
    "La invención de la imprenta por Johannes Gutenberg revolucionó la difusión de información",
    "La caída del Imperio Romano de Occidente en el año 476 d.C.",
    "La Revolución Industrial en Inglaterra en los siglos XVIII y XIX",
    "El descubrimiento del fuego por parte de los primeros seres humanos",
    "La Declaración de Independencia de los Estados Unidos en 1776",
    "La Revolución Cubana en 1959",
    "El Holocausto durante la Segunda Guerra Mundial",
    "El primer viaje a la Luna por parte de la misión Apollo 11 en 1969",
    "La caída del Muro de Berlín en 1989",
    "El Renacimiento en Europa durante los siglos XIV al XVI",
    "La Guerra Civil Española en 1936-1939",
    "El colapso del Imperio Otomano después de la Primera Guerra Mundial",
    "El Tratado de Versalles que puso fin a la Primera Guerra Mundial",
    "La construcción de la Gran Muralla China durante la dinastía Qin",
    "La abolición de la esclavitud en Estados Unidos con la Proclamación de Emancipación",
    "El surgimiento del nazismo en Alemania durante la década de 1930",
    "La firma de la Declaración de los Derechos Humanos en 1948",
    "La Revolución Industrial en Estados Unidos en el siglo XIX",
    "Adolf Hitler se suicida el 30 de abril de 1945",
    "La fundación del Imperio Romano por Rómulo y Remo",
    "El descubrimiento de la penicilina por Alexander Fleming en 1928",
    "El asesinato de Julio César en el año 44 a.C.",
    "El bombardeo de Hiroshima y Nagasaki al final de la Segunda Guerra Mundial",
    "La capital de Francia es París",
    "La capital de España es Madrid",
    "La capital de Italia es Roma",
    "La capital de Alemania es Berlín",
    "La capital de Estados Unidos es Washington D.C.",
    "El río más largo del mundo es el Nilo",
    "El océano más grande del mundo es el Océano Pacífico",
    "El monte más alto del mundo es el Monte Everest",
    "La ciudad más poblada del mundo es Tokio",
    "El animal más grande del mundo es la ballena azul",
    "El animal más rápido del mundo es el guepardo",
    "La flor más grande del mundo es la Rafflesia arnoldii",
    "El país más grande del mundo por área terrestre es Rusia",
    "El país más poblado del mundo es China",
    "El país más pequeño del mundo es la Ciudad del Vaticano",
    "El continente más grande del mundo es Asia",
    "El continente más poblado del mundo es Asia",
    "El océano más profundo del mundo es el Océano Pacífico",
    "El desierto más grande del mundo es el Desierto del Sahara",
    "El país con más islas del mundo es Suecia",
    "El país con más volcanes del mundo es Indonesia",
    "El país con más especies de mamíferos del mundo es Brasil",
    "El país con más especies de aves del mundo es Colombia",
    "El país con más especies de reptiles del mundo es Australia",
    "El país con más especies de anfibios del mundo es Brasil",
    "El país con más especies de peces de agua dulce del mundo es Brasil",
    "El país con más especies de plantas del mundo es Colombia",
    "El río más caudaloso del mundo es el Amazonas",
    "El lago más grande del mundo por superficie es el Mar Caspio",
    "El lago más profundo del mundo es el lago Baikal en Rusia",
    "El país más montañoso del mundo es Bután",
    "La isla más grande del mundo es Australia",
    "El país con más Patrimonios de la Humanidad de la UNESCO es Italia",
    "La ciudad más visitada del mundo es Bangkok, Tailandia",
    "La ciudad más cara del mundo para vivir es Singapur",
    "El monumento más famoso del mundo es la Gran Muralla China",
    "La montaña más alta fuera del Himalaya es el Monte Kilimanjaro",
    "El animal más venenoso del mundo es la medusa de caja",
    "La planta más venenosa del mundo es la adelfa",
    "El país con más selvas tropicales del mundo es Brasil",
    "El país con más desiertos del mundo es Australia",
    "El país con más idiomas reconocidos oficialmente es Papúa Nueva Guinea",
    "El país más diverso culturalmente del mundo es India",
    "El país más densamente poblado del mundo es Mónaco",
    "El país más rico del mundo es Qatar",
    "El país más antiguo del mundo es Egipto",
    "El país con más historia del mundo es China",
    "El país más extenso del mundo es Rusia",
    "El país más poblado del mundo es China",
    "La isla más poblada del mundo es Java en Indonesia",
    "El país con más habitantes musulmanes del mundo es Indonesia",
    "El país con más habitantes hindúes del mundo es India",
    "El país con más habitantes cristianos del mundo es Estados Unidos",
    "El país con más habitantes budistas del mundo es China",
    "El país con más habitantes judíos del mundo es Estados Unidos",
    "El país con más habitantes sij del mundo es India",
    "El país con más habitantes bahaíes del mundo es India",
    "El país con más habitantes zoroástricos del mundo es India",
    "El país con más habitantes taoístas del mundo es China",
    "El país con más habitantes confucianos del mundo es China",
    "El país con más habitantes animistas del mundo es Nigeria",
    "El país con más habitantes ateos del mundo es China",
    "El país con más habitantes agnósticos del mundo es China",
    "El país con más habitantes no religiosos del mundo es China",
    "El país con más habitantes que practican religiones tradicionales africanas es Nigeria",
    "El país con más habitantes que practican religiones tradicionales amerindias es México",
    "El país con más habitantes que practican religiones tradicionales asiáticas es India",
    "El país con más habitantes que practican religiones tradicionales europeas es Rusia",
    "El país con más habitantes que practican religiones tradicionales del Pacífico es Papúa Nueva Guinea",
    "El país con más habitantes que practican religiones sincréticas es Brasil",
    "El país con más habitantes que practican religiones indígenas es India",
    "El país con más habitantes que practican religiones afroamericanas es Nigeria",
    "El país con más habitantes que practican religiones afrocaribeñas es Brasil",
    "El país con más habitantes que practican religiones afrobrasileñas es Brasil",
    "El país con más habitantes que practican religiones afroamericanas y afrocaribeñas es Brasil",
    "El país con más habitantes que practican religiones afroamericanas, afrocaribeñas y afrobrasileñas es Brasil",
    "El país con más habitantes que practican religiones afroamericanas, afrocaribeñas, afrobrasileñas e indígenas es Brasil",
    "El país con más habitantes que practican religiones afroamericanas, afrocaribeñas, afrobrasileñas, indígenas y cristianas es Brasil",
    "El país con más habitantes que practican religiones afroamericanas, afrocaribeñas, afrobrasileñas, indígenas, cristianas y musulmanas es Brasil",
    "El país con más habitantes que practican religiones afroamericanas, afrocaribeñas, afrobrasileñas, indígenas, cristianas, musulmanas y judías es Brasil",
    "Hola, ¿cómo estás?",
    "¡Hola! ¿En qué puedo ayudarte?",
    "Buenos días, ¿en qué puedo servirte?",
    "¡Hola! ¿Qué tal tu día?",
    "Hola, ¿necesitas alguna asistencia?",
    "¡Buenas tardes! ¿Cómo puedo ayudarte hoy?",
    "Hola, ¿qué tal todo?",
    "¡Hola! ¿En qué puedo colaborar contigo?",
    "Hola, ¿cómo puedo ayudarte en el día de hoy?",
    "¡Buen día! ¿Cómo estás?",
    "Hola, ¿qué puedo hacer por ti?",
    "¡Hola! ¿Necesitas algo en particular?",
    "Buenos días, ¿cómo estás hoy?",
    "Hola, ¿hay algo en lo que pueda asistirte?",
    "¡Hola! ¿Cómo estás llevando el día?",
    "Me alegra escuchar que estés bien.",
    "Qué bueno que todo esté bien contigo.",
    "Estoy bien, gracias por preguntar.",
    "Todo bien por aquí, ¿y tú?",
    "Estoy bien, gracias. ¿En qué puedo ayudarte?",
    "Excelente, ¿en qué puedo asistirte hoy?",
    "Todo tranquilo por aquí, ¿y contigo?",
    "Estoy bien, ¿hay algo en lo que pueda colaborarte?",
    "Me encuentro bien, ¿necesitas ayuda con algo en particular?",
    "¡Genial! ¿En qué puedo servirte?",
    "Todo en orden, ¿cómo puedo ayudarte?",
    "Estoy bien, gracias. ¿Qué necesitas?",
    "Bien, ¿cómo va todo contigo?",
    "Todo bien por acá, ¿en qué puedo ayudarte?",
    "Qué bueno que estés bien. ¿En qué puedo colaborar?",
    "La Tierra es el tercer planeta del sistema solar.",
    "El sistema solar está compuesto por ocho planetas.",
    "La velocidad de la luz es aproximadamente 299,792,458 metros por segundo en el vacío.",
    "El átomo es la unidad básica de la materia.",
    "La teoría de la relatividad fue desarrollada por Albert Einstein.",
    "La ley de la gravitación universal fue formulada por Isaac Newton.",
    "El ADN contiene la información genética de los seres vivos.",
    "La fotosíntesis es el proceso mediante el cual las plantas convierten la luz solar en energía.",
    "El símbolo químico del agua es H2O.",
    "La energía no se crea ni se destruye, solo se transforma.",
    "La ley de la conservación de la energía es un principio fundamental en la física.",
    "La primera ley de la termodinámica establece que la energía total de un sistema aislado se mantiene constante.",
    "La segunda ley de la termodinámica establece que la entropía de un sistema cerrado siempre tiende a aumentar con el tiempo.",
    "La ley de Ohm describe la relación entre la corriente eléctrica, la diferencia de potencial y la resistencia eléctrica.",
    "La tabla periódica de los elementos organiza los elementos químicos en función de sus propiedades y estructura atómica.",
    "El Big Bang es la teoría científica predominante sobre el origen del universo.",
    "La evolución biológica es el proceso mediante el cual las especies cambian a lo largo del tiempo a través de la selección natural.",
    "La relatividad general es la teoría de la gravedad propuesta por Albert Einstein en 1915.",
    "El número pi (π) es una constante matemática que representa la relación entre la circunferencia de un círculo y su diámetro.",
    "El teorema de Pitágoras establece que en un triángulo rectángulo, el cuadrado de la longitud de la hipotenusa es igual a la suma de los cuadrados de las longitudes de los otros dos lados.",
    "La ley de la oferta y la demanda es un principio económico que establece que el precio de un bien o servicio aumenta cuando la demanda es mayor que la oferta y disminuye cuando la oferta es mayor que la demanda.",
    "La democracia es un sistema de gobierno en el cual el poder político es ejercido por el pueblo a través de mecanismos de participación ciudadana como elecciones y referendos.",
    "La Revolución Industrial fue un período de transformación económica y social que comenzó en Gran Bretaña en el siglo XVIII y se extendió por Europa y América en los siglos siguientes.",
    "La Revolución Francesa fue un período de agitación política y social en Francia que tuvo lugar entre 1789 y 1799, y que marcó el fin del Antiguo Régimen y el comienzo de la era moderna.",
    "La Segunda Guerra Mundial fue un conflicto global que tuvo lugar entre 1939 y 1945, en el que las potencias aliadas lucharon contra las potencias del Eje, lideradas por Alemania, Italia y Japón.",
    "La teoría de la evolución de Charles Darwin propone que las especies evolucionan a lo largo del tiempo a través de un proceso de selección natural, en el que los organismos mejor adaptados a su entorno tienen más probabilidades de sobrevivir y reproducirse.",
    "La teoría del Big Bang postula que el universo comenzó como una singularidad extremadamente caliente y densa hace aproximadamente 13.800 millones de años, y desde entonces ha estado en constante expansión y enfriamiento.",
    "La teoría cuántica es el marco teórico que describe el comportamiento de las partículas subatómicas, como electrones y fotones, y que es fundamental para entender fenómenos como la mecánica cuántica y la electrodinámica cuántica.",
    "La teoría de la relatividad de Albert Einstein revolucionó nuestra comprensión del espacio, el tiempo y la gravedad, al postular que las leyes de la física son las mismas para todos los observadores, independientemente de su estado de movimiento, y que la gravedad es la curvatura del espacio-tiempo causada por la presencia de masa y energía.",
    "La ley de la gravitación universal de Isaac Newton establece que cada partícula de materia atrae a cada otra partícula con una fuerza que es directamente proporcional al producto de sus masas e inversamente proporcional al cuadrado de la distancia entre ellas.",
    "La tabla periódica de los elementos fue propuesta por primera vez por Dmitri Mendeléyev en 1869, y es una disposición de los elementos químicos en forma de tabla, ordenados por su número atómico, configuración electrónica y propiedades químicas.",
    "La ley de la conservación de la energía, también conocida como el primer principio de la termodinámica, establece que la energía total de un sistema aislado permanece constante con el tiempo, es decir, la energía no puede crearse ni destruirse, solo puede transformarse de una forma a otra.",
    "La ley de la entropía, también conocida como el segundo principio de la termodinámica, establece que la entropía de un sistema aislado tiende a aumentar con el tiempo, lo que implica que los sistemas tienden a evolucionar hacia estados de mayor desorden o aleatoriedad.",
    "El átomo es la unidad básica de la materia, compuesta por un núcleo central de protones y neutrones, rodeado por electrones que orbitan alrededor del núcleo en niveles de energía.",
    "El ADN, o ácido desoxirribonucleico, es una molécula que lleva la información genética de los seres vivos, y está compuesta por una cadena de nucleótidos que contienen las bases nitrogenadas adenina, timina, citosina y guanina.",
    "La fotosíntesis es el proceso mediante el cual las plantas, algas y algunas bacterias utilizan la luz solar para convertir el dióxido de carbono y el agua en glucosa y oxígeno, liberando oxígeno como subproducto.",
    "La velocidad de la luz en el vacío es una constante física fundamental que tiene un valor aproximado de 299,792,458 metros por segundo, y es la velocidad máxima a la que puede viajar la información o la energía en el universo.",
    "El átomo, descubierto por primera vez en el siglo V a.C. por el filósofo griego Leucipo y su discípulo Demócrito, es la unidad básica de la materia, compuesto por un núcleo central de protones y neutrones, rodeado por electrones que orbitan alrededor del núcleo en niveles de energía.",
    "El agua, compuesta por dos átomos de hidrógeno y uno de oxígeno, es una sustancia esencial para la vida en la Tierra, y es un solvente universal que participa en una amplia gama de procesos bioquímicos y físicos.",
    "La Tierra es el tercer planeta del sistema solar y el único conocido por albergar vida. Tiene una atmósfera compuesta principalmente de nitrógeno y oxígeno, y su superficie está cubierta en su mayoría por agua.",
    "La Segunda Guerra Mundial fue un conflicto global que tuvo lugar entre 1939 y 1945, en el que las potencias aliadas, lideradas por Estados Unidos, el Reino Unido y la Unión Soviética, lucharon contra las potencias del Eje, lideradas por Alemania, Italia y Japón.",
    "El sistema solar está compuesto por el sol, ocho planetas principales, sus lunas y otros objetos celestes que orbitan alrededor del sol, como asteroides, cometas y planetas enanos.",
    "La ley de la gravitación universal de Isaac Newton establece que cada partícula de materia atrae a cada otra partícula con una fuerza que es directamente proporcional al producto de sus masas e inversamente proporcional al cuadrado de la distancia entre ellas.",
    "La democracia es un sistema de gobierno en el que el poder político es ejercido por el pueblo a través de mecanismos de participación ciudadana como elecciones y referendos, y se basa en el respeto a los derechos humanos, la libertad de expresión y la separación de poderes.",
    "El sol es una estrella ubicada en el centro del sistema solar, que contiene aproximadamente el 99.8% de la masa total del sistema solar y proporciona la energía necesaria para sustentar la vida en la Tierra a través de la radiación electromagnética.",
    "La teoría de la relatividad de Albert Einstein, formulada en 1905 y 1915, revolucionó nuestra comprensión del espacio, el tiempo y la gravedad, al postular que las leyes de la física son las mismas para todos los observadores, independientemente de su estado de movimiento, y que la gravedad es la curvatura del espacio-tiempo causada por la presencia de masa y energía.",
    "La ley de la oferta y la demanda es un principio económico fundamental que establece que el precio de un bien o servicio aumenta cuando la demanda es mayor que la oferta, y disminuye cuando la oferta es mayor que la demanda.",
    "El átomo, descubierto por primera vez en el siglo V a.C. por el filósofo griego Leucipo y su discípulo Demócrito, es la unidad básica de la materia, compuesto por un núcleo central de protones y neutrones, rodeado por electrones que orbitan alrededor del núcleo en niveles de energía.",
    "La velocidad de la luz en el vacío es una constante física fundamental que tiene un valor aproximado de 299,792,458 metros por segundo, y es la velocidad máxima a la que puede viajar la información o la energía en el universo.",
    "El sistema solar está compuesto por el sol, ocho planetas principales, sus lunas y otros objetos celestes que orbitan alrededor del sol, como asteroides, cometas y planetas enanos.",
    "La ley de la gravitación universal de Isaac Newton establece que cada partícula de materia atrae a cada otra partícula con una fuerza que es directamente proporcional al producto de sus masas e inversamente proporcional al cuadrado de la distancia entre ellas.",
    "La democracia es un sistema de gobierno en el que el poder político es ejercido por el pueblo a través de mecanismos de participación ciudadana como elecciones y referendos, y se basa en el respeto a los derechos humanos, la libertad de expresión y la separación de poderes.",
]

stop_words = set(stopwords.words('spanish'))

def preprocess_text(text):
    tokens = word_tokenize(text.lower())
    filtered_tokens = [word for word in tokens if word.isalpha() and word not in stop_words] 
    return ' '.join(filtered_tokens) 

processed_data = [preprocess_text(text) for text in data]

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(processed_data)

def answer_question(question):
    processed_question = preprocess_text(question)
    question_vector = vectorizer.transform([processed_question])
    similarity_scores = cosine_similarity(question_vector, tfidf_matrix)
    best_index = similarity_scores.argmax()
    best_score = similarity_scores[0, best_index]
    
    threshold = 0.2
    
    if best_score < threshold:
        return "Lo siento, no tengo una respuesta para esa pregunta. Podrías agregarla a la base de datos."
    else:
        return data[best_index]